// <auto-generated />
using System;
using Kaleido.Modules.Services.Grpc.Products.Common.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kaleido.Modules.Services.Grpc.Products.Migrations.Migrations
{
    [DbContext(typeof(ProductPriceEntityDbContext))]
    [Migration("20241116130822_ProductPriceEntity")]
    partial class ProductPriceEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kaleido.Modules.Services.Grpc.Products.Common.Models.ProductPriceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyKey")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("ProductKey")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<float>("Value")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id");

                    b.ToTable("ProductPrices", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
