syntax = "proto3";

package Kaleido.Grpc.Products;

import "models.proto";

service GrpcProducts {
  rpc GetProduct(ProductRequest) returns (ProductResponse) {}
  rpc CreateProduct(Product) returns (ProductResponse) {}
  rpc UpdateProduct(ProductActionRequest) returns (ProductResponse) {}
  rpc DeleteProduct(ProductRequest) returns (ProductResponse) {}
  rpc GetProductRevisions(ProductRequest) returns (ProductListResponse) {}
  rpc GetProductRevision(ProductRevisionRequest) returns (ProductResponse) {}
  rpc GetAllProducts(EmptyRequest) returns (ProductListResponse) {}
  rpc GetAllProductsByCategoryKey(ProductByCategoryRequest) returns (ProductListResponse) {}
  rpc GetAllProductsByName(ProductByNameRequest) returns (ProductListResponse) {}
  rpc GetAllProductsByCategoryKeyAndName(ProductByCategoryAndNameRequest) returns (ProductListResponse) {}
}