name: CI Pipeline on Pull Request

'on': pull_request

jobs:
  gitversion:
    name: GitVersion
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.Semver.outputs.MajorMinorPatch }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository
        with:
          fetch-depth: 0
      - uses: gittools/actions/gitversion/setup@v3.0.0
      - id: Semver
        uses: gittools/actions/gitversion/execute@v3.0.0

  build-products-service:
    name: Build Products Service
    needs: gitversion
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository
      - name: Add Github nugetfeed
        run: dotnet nuget add source --username DriesDelanghe --password ${{ secrets.NUGET_GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Kaleido-organisation-manager/index.json"
      - name: Restore dependencies of products service
        run: dotnet restore 
        working-directory: src/Kaleido.Modules.Services.Grpc.Products
      - name: Build products service
        run: dotnet build
        working-directory: src/Kaleido.Modules.Services.Grpc.Products

  build-products-service-migrations:
    name: Build Products Service Migrations
    needs: gitversion
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository
      - name: Add Github nugetfeed
        run: dotnet nuget add source --username DriesDelanghe --password ${{ secrets.NUGET_GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Kaleido-organisation-manager/index.json"
      - name: Restore dependencies of products service migrations
        run: dotnet restore
        working-directory: src/Kaleido.Modules.Services.Grpc.Products.Migrations
      - name: Build products service migrations
        run: dotnet build
        working-directory: src/Kaleido.Modules.Services.Grpc.Products.Migrations

  build-products-service-client:
    name: Build Products Service Client
    needs: gitversion
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository
      - name: Add Github nugetfeed
        run: dotnet nuget add source --username DriesDelanghe --password ${{ secrets.NUGET_GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Kaleido-organisation-manager/index.json"
      - name: Restore dependencies of products service client
        run: dotnet restore
        working-directory: src/Kaleido.Modules.Services.Grpc.Products.Client
      - name: Build products service client
        run: dotnet build
        working-directory: src/Kaleido.Modules.Services.Grpc.Products.Client

  unit-tests:
    name: Run Unit Tests
    needs: [build-products-service, build-products-service-migrations, build-products-service-client]
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository
      - name: Add Github nugetfeed
        run: dotnet nuget add source --username DriesDelanghe --password ${{ secrets.NUGET_GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Kaleido-organisation-manager/index.json"
      - name: Restore dependencies of unit tests
        run: dotnet restore
        working-directory: src/Kaleido.Modules.Services.Grpc.Products.Tests.Unit
      - name: Run unit tests
        run: dotnet test
        working-directory: src/Kaleido.Modules.Services.Grpc.Products.Tests.Unit

  create-service-release:
    name: Create Dotnet Release for service
    runs-on: ubuntu-latest
    needs: [build-products-service, build-products-service-migrations, build-products-service-client, gitversion]
    permissions:
      packages: read
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository
      - name: Add Github nugetfeed
        run: dotnet nuget add source --username DriesDelanghe --password ${{ secrets.NUGET_GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Kaleido-organisation-manager/index.json"
      - name: Restore dependencies of service
        run: dotnet restore
        working-directory: src/Kaleido.Modules.Services.Grpc.Products
      - name: Build service Release
        run: dotnet build -c Release
        working-directory: src/Kaleido.Modules.Services.Grpc.Products
      - name: Upload Dotnet Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: products-service
          path: src/Kaleido.Modules.Services.Grpc.Products/bin/Release/net8.0

  create-migrations-release:
    name: Create Dotnet Release for migrations
    runs-on: ubuntu-latest
    needs: [build-products-service, build-products-service-migrations, build-products-service-client, gitversion]
    permissions:
      packages: read
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository
      - name: Add Github nugetfeed
        run: dotnet nuget add source --username DriesDelanghe --password ${{ secrets.NUGET_GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Kaleido-organisation-manager/index.json"
      - name: Restore dependencies of migrations
        run: dotnet restore
        working-directory: src/Kaleido.Modules.Services.Grpc.Products.Migrations
      - name: Build migrations
        run: dotnet build -c Release
        working-directory: src/Kaleido.Modules.Services.Grpc.Products.Migrations
      - name: Upload Dotnet Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: products-service-migrations
          path: src/Kaleido.Modules.Services.Grpc.Products.Migrations/bin/Release/net8.0

  integration-tests:
    name: Run Integration Tests
    needs: [create-service-release, create-migrations-release, gitversion]
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository
      - name: Add Github nugetfeed
        run: dotnet nuget add source --username DriesDelanghe --password ${{ secrets.NUGET_GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Kaleido-organisation-manager/index.json"
      - name: Restore dependencies of integration tests
        run: dotnet restore
        working-directory: src/Kaleido.Modules.Services.Grpc.Products.Tests.Integrations
      - name: Download Service Release Artifact
        uses: actions/download-artifact@v4
        with:
          name: products-service
          path: $GITHUB_WORKSPACE/service/out
      - name: Download Migrations Release Artifact
        uses: actions/download-artifact@v4
        with:
          name: products-service-migrations
          path: $GITHUB_WORKSPACE/migrations/out
      - name: Build Product Service Docker Image
        run: docker build . -f dockerfiles/Grpc.Products/Dockerfile.cicd -t kaleido-modules-services-grpc-products:${{ needs.gitversion.outputs.version }} --build-arg RELEASE_DIR=$GITHUB_WORKSPACE/service/out
      - name: Build Migrations Docker Image
        run: docker build . -f dockerfiles/Grpc.Products.Migrations/Dockerfile.cicd -t kaleido-modules-services-grpc-products-migrations:${{ needs.gitversion.outputs.version }} --build-arg RELEASE_DIR=$GITHUB_WORKSPACE/migrations/out
      - name: Run integration tests
        run: dotnet test
        working-directory: src/Kaleido.Modules.Services.Grpc.Products.Tests.Integrations
        env:
          PRODUCTS_IMAGE_NAME: kaleido-modules-services-grpc-products:${{ needs.gitversion.outputs.version }}
          MIGRATIONS_IMAGE_NAME: kaleido-modules-services-grpc-products-migrations:${{ needs.gitversion.outputs.version }}
          CI: true
