name: CI Pipeline on Pull Request

'on': pull_request

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      # ================================================
      # CHECKOUT
      # ================================================
      - uses: actions/checkout@v4

      # ================================================
      # BUILD AND RESTORE DEPENDENCIES
      # ================================================
      - name: 'Restore dependencies'
        run: dotnet restore
        working-directory: src
      - name: 'Build service project'
        run: dotnet build
        working-directory: src/Kaleido.Modules.Services.Grpc.Products
      - name: 'Build migrations project'
        run: dotnet build
        working-directory: src/Kaleido.Modules.Services.Grpc.Products.Migrations
      - name: 'Build client project'
        run: dotnet build
        working-directory: src/Kaleido.Modules.Services.Grpc.Products.Client

      # ================================================
      # RUN TESTS
      # ================================================
      - name: 'Run unit tests'
        run: dotnet test
        working-directory: src/Kaleido.Modules.Services.Grpc.Products.Tests.Unit

      # ================================================
      # RUN INTEGRATION TESTS
      # ================================================
      - name: 'Check Docker'
        run: docker info
      - name: 'Run integration tests'
        run: dotnet test
        working-directory: src/Kaleido.Modules.Services.Grpc.Products.Tests.Integrations

      # ================================================
      # DOCKER BUILD
      # ================================================
      - name: 'Build docker service image'
        run: docker build . -f docker/Grpc.Products.Service/Dockerfile -t kaleido-modules-services-grpc-products:${{ github.run_number }}
      - name: 'Build docker migrations image'
        run: docker build . -f docker/Grpc.Products.Migrations/Dockerfile -t kaleido-modules-services-grpc-products-migrations:${{ github.run_number }}

