name: CI Pipeline on Pull Request

'on': pull_request

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      # ================================================
      # CHECKOUT
      # ================================================
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ================================================
      # GITVERSION
      # ================================================
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: '6.x'

      - name: Execute GitVersion
        id: Semver
        uses: gittools/actions/gitversion/execute@v3.0.0

      # ================================================
      # BUILD AND RESTORE DEPENDENCIES
      # ================================================
      - name: 'Restore dependencies'
        run: dotnet restore
        working-directory: src
      - name: 'Build service project'
        run: dotnet build
        working-directory: src/Kaleido.Modules.Services.Grpc.Products
      - name: 'Build migrations project'
        run: dotnet build
        working-directory: src/Kaleido.Modules.Services.Grpc.Products.Migrations
      - name: 'Build client project'
        run: dotnet build
        working-directory: src/Kaleido.Modules.Services.Grpc.Products.Client

      # ================================================
      # DOCKER BUILD
      # ================================================
      - name: 'Build docker service image'
        run: docker build . -f dockerfiles/Grpc.Products.Service/Dockerfile -t kaleido-modules-services-grpc-products:${{ steps.Semver.outputs.MajorMinorPatch }}
      - name: 'Build docker migrations image'
        run: docker build . -f dockerfiles/Grpc.Products.Migrations/Dockerfile -t kaleido-modules-services-grpc-products-migrations:${{ steps.Semver.outputs.MajorMinorPatch }}

      # ================================================
      # RUN TESTS
      # ================================================
      - name: 'Run unit tests'
        run: dotnet test
        working-directory: src/Kaleido.Modules.Services.Grpc.Products.Tests.Unit

      # ================================================
      # RUN INTEGRATION TESTS
      # ================================================
      - name: 'Check Docker'
        run: docker info
      - name: 'Run integration tests'
        run: dotnet test --logger "console;verbosity=detailed"
        working-directory: src/Kaleido.Modules.Services.Grpc.Products.Tests.Integrations
        env:
          PRODUCTS_IMAGE_NAME: kaleido-modules-services-grpc-products:${{ steps.Semver.outputs.MajorMinorPatch }}
          MIGRATIONS_IMAGE_NAME: kaleido-modules-services-grpc-products-migrations:${{ steps.Semver.outputs.MajorMinorPatch }}
          CI: true

